# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZLC3niEGaH30TMvPC1SdtRHZmsiPDns
"""

!mkdir -p streamlit_app

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app/app.py
# import streamlit as st
# import requests
# 
# st.title("Skill Trend Detector")
# 
# description = st.text_area("Paste Job Description")
# if st.button("Analyze"):
#     if description:
#         response = requests.post("http://127.0.0.1:8000/skill-trend", json={"job_description": description})
#         if response.status_code == 200:
#             result = response.json()
#             st.json(result)
#         else:
#             st.error("API Error")
#     else:
#         st.warning("Please enter a description")
#